import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import { Roboto } from 'next/font/google';
import Providers from '@/redux/Providers';
import Footer from '@/components/Footer';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
